apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM2akNDQWRLZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJeU1EY3hPVEExTVRneE9Gb1hEVE15TURjeE5qQTFNak14T0Zvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTU42Cnc2NWJnYUFaZDJPRG5CK1NDK1NxeUVQbCtic1c3dURXQy8yclcrWEx4d3FRR0l3SmY0UVlPTGdsUlFtMFNEd0kKYXhWaHlOVlFHeGJuSEt6REE2YXcraWw0ekYwTXN6dEhSMlRmemJqclBZWnAxcmFSbUxZYTVHRWlWVG9uTVZOUQpvWU92VncwbzNUYW43MVBIY3QzbEExQzhHbklpaEFUZWM5bUI1dTM3SlhTeGhUZk1vMzVqSGp2eE9qbTVwamxuClZCNEo1OElCUDl4NkhvbEpNejQrUVBoK2FTMUtmQ2hxSEd3NFhDbnZjY3BFZ3VOYlhqZmwySkE2NHhJTmoyWncKeXZ2WXBEWXhsT1k1azgvNnNsYmRoN2I4ZGdGLzV6RzNWN0VFODZ3NVZ1MksrLzlrYVArUGtjUzVpVTd0c3VIQQpQclczb2V1VG9vN3FKMWxOTVdVQ0F3RUFBYU5GTUVNd0RnWURWUjBQQVFIL0JBUURBZ0trTUJJR0ExVWRFd0VCCi93UUlNQVlCQWY4Q0FRQXdIUVlEVlIwT0JCWUVGTnJONFNJQVp0aVFtYkozWEp3a0ZWY1ZWNzU3TUEwR0NTcUcKU0liM0RRRUJDd1VBQTRJQkFRQk1TdWVPSzk1MHU0aU1sS1BUUTJvZlAvcndFVWJiSkJwL0NCV0UybTR3Tzd3YQpoVDdSS0NrYVpCOFFLUmgvK2IwVHUyWXRNNmc0elM1ZTRQMXBOMVlpRFI4YlNJOGhvUXdSeXRDbSs4b25JbG82CjVrdnVPdW9LclgzOGNOMjFLVjN4NzBoNU14Q25HRjVFM2h2cGk0UWZDeG1CWi92Zi9ZWWZNOVFxd3dkRlFMSFAKVU0xYnNxZjMzWXNQU281dXVTMmwydEVoaHp0UnhWQ29SNTVXRnFmNXduREtvaGhOR094NDhYVGlOdVdyeWlLTwpjUk04UktoZjFkR01LV0t1ck9zY0hjMldDa28wNVladVdYVENCTEJJdURYNjdrTzd2V2RGNTIycnZ4b2s2MXRFClJYcWp5eEhOREhyNWNuVkNLaU9vMWVwSlhNcFFZU1owMTN6eDYzdDEKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    server: https://jowett-tkg-apiserver-840457389.ap-southeast-1.elb.amazonaws.com:6443
  name: jowett-tkg
contexts:
- context:
    cluster: jowett-tkg
    namespace: default
    user: jowett-tkg
  name: jowett-tkg
current-context: jowett-tkg
kind: Config
preferences: {}
users:
- name: jowett-tkg
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - cluster
      - generate-token-v2
      command: tmc
      env:
      - name: CLUSTER_UID
        value: c:01G8AEB2XPRA1N56R8A4P7166M
      - name: CLUSTER_RID_V2
        value: rid:c:1ea829de-224f-4413-86c0-636173e503e9:tk-aws-hosted:default:jowett-tkg
      - name: CLUSTER_ENDPOINT
        value: https://jowett-tkg-apiserver-840457389.ap-southeast-1.elb.amazonaws.com:6443
      - name: CLUSTER_CA_BUNDLE
        value: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM2akNDQWRLZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJeU1EY3hPVEExTVRneE9Gb1hEVE15TURjeE5qQTFNak14T0Zvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTU42Cnc2NWJnYUFaZDJPRG5CK1NDK1NxeUVQbCtic1c3dURXQy8yclcrWEx4d3FRR0l3SmY0UVlPTGdsUlFtMFNEd0kKYXhWaHlOVlFHeGJuSEt6REE2YXcraWw0ekYwTXN6dEhSMlRmemJqclBZWnAxcmFSbUxZYTVHRWlWVG9uTVZOUQpvWU92VncwbzNUYW43MVBIY3QzbEExQzhHbklpaEFUZWM5bUI1dTM3SlhTeGhUZk1vMzVqSGp2eE9qbTVwamxuClZCNEo1OElCUDl4NkhvbEpNejQrUVBoK2FTMUtmQ2hxSEd3NFhDbnZjY3BFZ3VOYlhqZmwySkE2NHhJTmoyWncKeXZ2WXBEWXhsT1k1azgvNnNsYmRoN2I4ZGdGLzV6RzNWN0VFODZ3NVZ1MksrLzlrYVArUGtjUzVpVTd0c3VIQQpQclczb2V1VG9vN3FKMWxOTVdVQ0F3RUFBYU5GTUVNd0RnWURWUjBQQVFIL0JBUURBZ0trTUJJR0ExVWRFd0VCCi93UUlNQVlCQWY4Q0FRQXdIUVlEVlIwT0JCWUVGTnJONFNJQVp0aVFtYkozWEp3a0ZWY1ZWNzU3TUEwR0NTcUcKU0liM0RRRUJDd1VBQTRJQkFRQk1TdWVPSzk1MHU0aU1sS1BUUTJvZlAvcndFVWJiSkJwL0NCV0UybTR3Tzd3YQpoVDdSS0NrYVpCOFFLUmgvK2IwVHUyWXRNNmc0elM1ZTRQMXBOMVlpRFI4YlNJOGhvUXdSeXRDbSs4b25JbG82CjVrdnVPdW9LclgzOGNOMjFLVjN4NzBoNU14Q25HRjVFM2h2cGk0UWZDeG1CWi92Zi9ZWWZNOVFxd3dkRlFMSFAKVU0xYnNxZjMzWXNQU281dXVTMmwydEVoaHp0UnhWQ29SNTVXRnFmNXduREtvaGhOR094NDhYVGlOdVdyeWlLTwpjUk04UktoZjFkR01LV0t1ck9zY0hjMldDa28wNVladVdYVENCTEJJdURYNjdrTzd2V2RGNTIycnZ4b2s2MXRFClJYcWp5eEhOREhyNWNuVkNLaU9vMWVwSlhNcFFZU1owMTN6eDYzdDEKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
      provideClusterInfo: false
